/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school_management.library_management;

import java.awt.event.KeyEvent;
import java.sql.Connection;
//import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
//import java.util.Calendar;
//import java.util.Locale;
import javax.swing.JOptionPane;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import school_management.DBConn;
/**
 *
 * @author Umani Welisara
 */
public class IssueBooksUI extends javax.swing.JFrame {

    /**
     * Creates new form payment
     */
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public IssueBooksUI() {
        initComponents();
        bbbid_1.setText("");
        bbbid_2.setText("");
        bbmid.setText("");

        conn = DBConn.myConn();


        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Calendar cal = Calendar.getInstance();
        System.out.println(df.format(cal.getTime()));
        lblcdate.setText(df.format(cal.getTime()));
        
        //get the current date
        Date currentDate = new Date();
        //DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        System.out.println(df.format(currentDate));

        // convert date to calendar
        Calendar c = Calendar.getInstance();
        c.setTime(currentDate);
        // manipulate date
        c.add(Calendar.DATE, 7);
        // convert calendar to date
        Date currentDatePlusOne = c.getTime();
        System.out.println(df.format(currentDatePlusOne));

        lblrdate.setText(df.format(currentDatePlusOne));
// ...................................................................

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bbmid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bbbid_1 = new javax.swing.JTextField();
        bbbid_2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblcdate = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblrdate = new javax.swing.JLabel();
        btnbbborrow = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("    BORROW BOOKS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, 230, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Member ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        bbmid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bbmid.setText("jTextField1");
        bbmid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bbmidKeyTyped(evt);
            }
        });
        getContentPane().add(bbmid, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 190, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Book ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        bbbid_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bbbid_1.setText("jTextField1");
        bbbid_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bbbid_1KeyTyped(evt);
            }
        });
        getContentPane().add(bbbid_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 190, -1));

        bbbid_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bbbid_2.setText("jTextField1");
        bbbid_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bbbid_2KeyTyped(evt);
            }
        });
        getContentPane().add(bbbid_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 190, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Current Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        lblcdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblcdate.setText("jLabel5");
        getContentPane().add(lblcdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 170, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Return Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        lblrdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblrdate.setText("jLabel5");
        getContentPane().add(lblrdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 170, 30));

        btnbbborrow.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnbbborrow.setText("BORROW");
        btnbbborrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbbborrowActionPerformed(evt);
            }
        });
        getContentPane().add(btnbbborrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 310, 50));

        jButton1.setText("<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 60, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school_management/library_management/images/lms-2.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -580, 1320, 1020));

        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        setSize(new java.awt.Dimension(1196, 479));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnbbborrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbbborrowActionPerformed
        // TODO add your handling code here:

        String memid = bbmid.getText();
        String book1 = bbbid_1.getText();
        String book2 = bbbid_2.getText();
        String cdate = lblcdate.getText();
        String rdate = lblrdate.getText();

        IssueBooksModel ibm = new IssueBooksModel(memid, book1, book2, cdate, rdate);

        boolean successStatus = ibm.insertIssueBook();
        if (successStatus) {
            JOptionPane.showMessageDialog(this, "Successfully inserted to db");

            bbmid.setText("");
            bbbid_1.setText("");
            bbbid_2.setText("");
           
          
        } else {
            JOptionPane.showMessageDialog(this, "Error in inserting to db");
        }


    }//GEN-LAST:event_btnbbborrowActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new LibraryHomeUI().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void bbmidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bbmidKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)|| c==KeyEvent.VK_DELETE)){
        evt.consume();
        }
    }//GEN-LAST:event_bbmidKeyTyped

    private void bbbid_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bbbid_1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)|| c==KeyEvent.VK_DELETE)){
        evt.consume();
        }
    }//GEN-LAST:event_bbbid_1KeyTyped

    private void bbbid_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bbbid_2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)|| c==KeyEvent.VK_DELETE)){
        evt.consume();
        }
    }//GEN-LAST:event_bbbid_2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBooksUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBooksUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBooksUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBooksUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBooksUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bbbid_1;
    private javax.swing.JTextField bbbid_2;
    private javax.swing.JTextField bbmid;
    private javax.swing.JButton btnbbborrow;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblcdate;
    private javax.swing.JLabel lblrdate;
    // End of variables declaration//GEN-END:variables
}
