/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school_management.library_management;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import school_management.DBConn;
/**
 *
 * @author Umani Welisara
 */
public class ReturnBooksUI extends javax.swing.JFrame {

    /**
     * Creates new form ReturnBooksUI
     */
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public ReturnBooksUI() {
        initComponents();
        rmemid.setText("");
        rbid1.setText("");
        rbid2.setText("");
        rdayfine.setText("");
        lrtotfine.setText("N/A");

        conn = DBConn.myConn();
    }
    //today
    DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
    Calendar cal = Calendar.getInstance();
//System.out.println(df.format(cal.getTime()));

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbid1 = new javax.swing.JTextField();
        rbid2 = new javax.swing.JTextField();
        rmemid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rdayfine = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lrtotfine = new javax.swing.JLabel();
        btnrreturn = new javax.swing.JButton();
        btnfinedayok = new javax.swing.JButton();
        btnmemidok = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1200, 480));
        setMinimumSize(new java.awt.Dimension(1170, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Member ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Book ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        rbid1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbid1.setText("jTextField1");
        jPanel1.add(rbid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 136, 30));

        rbid2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbid2.setText("jTextField1");
        jPanel1.add(rbid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 136, 30));

        rmemid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rmemid.setText("jTextField1");
        rmemid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmemidActionPerformed(evt);
            }
        });
        jPanel1.add(rmemid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 136, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Fine per Day");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        rdayfine.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdayfine.setText("jTextField1");
        jPanel1.add(rdayfine, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 136, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Total Fine");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 214, -1, 20));

        lrtotfine.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lrtotfine.setText("jLabel5");
        jPanel1.add(lrtotfine, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 136, 30));

        btnrreturn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnrreturn.setText("RETURN");
        btnrreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrreturnActionPerformed(evt);
            }
        });
        jPanel1.add(btnrreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 90, 48));

        btnfinedayok.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnfinedayok.setText("OK");
        btnfinedayok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfinedayokActionPerformed(evt);
            }
        });
        jPanel1.add(btnfinedayok, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 50, 30));

        btnmemidok.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnmemidok.setText("OK");
        btnmemidok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmemidokActionPerformed(evt);
            }
        });
        jPanel1.add(btnmemidok, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 50, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 450, 340));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("    RETURN BOOKS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 220, 30));

        jButton1.setText("<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, 70, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school_management/library_management/images/lms-2.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 460));

        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new LibraryHomeUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnmemidokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmemidokActionPerformed
        try {
            // TODO add your handling code here:
            String memid = rmemid.getText();
            String book1 = rbid1.getText();
            String book2 = rbid2.getText();
            String dayfine = rdayfine.getText();
            String totfine = lrtotfine.getText();

            ReturnBooksModel r1 = new ReturnBooksModel(memid, book1, book2, dayfine, totfine);

            rbid1.setText(r1.showBooks1());
            rbid2.setText(r1.showBooks2());

            // showBooks();
        } catch (SQLException ex) {
            Logger.getLogger(ReturnBooksUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnmemidokActionPerformed

    private void btnfinedayokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfinedayokActionPerformed
        try {
            // TODO add your handling code here:

            String memid = rmemid.getText();
            String book1 = rbid1.getText();
            String book2 = rbid2.getText();
            String dayfine = rdayfine.getText();
            String totfine = lrtotfine.getText();

            ReturnBooksModel r2 = new ReturnBooksModel(memid, book1, book2, dayfine, totfine);

            float dayf = Float.parseFloat(dayfine);
            float calc = dayf * r2.countdays();
            String s = Float.toString(calc);
            lrtotfine.setText(s);

        } catch (SQLException ex) {
            Logger.getLogger(ReturnBooksUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnfinedayokActionPerformed

    private void btnrreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrreturnActionPerformed
        // TODO add your handling code here:

        String memid = rmemid.getText();
        String book1 = rbid1.getText();
        String book2 = rbid2.getText();
        String dayfine = rdayfine.getText();
        String totfine = lrtotfine.getText();

        ReturnBooksModel rbm = new ReturnBooksModel(memid, book1, book2, dayfine, totfine);

        boolean successStatus = rbm.insertReturnBook();
        if (successStatus) {
            JOptionPane.showMessageDialog(this, "Successfully inserted to db");

            rmemid.setText("");
            rbid1.setText("");
            rbid2.setText("");
            rdayfine.setText("");
            lrtotfine.setText("N/A");
        } else {
            JOptionPane.showMessageDialog(this, "Error in inserting to db");
        }

    }//GEN-LAST:event_btnrreturnActionPerformed

    private void rmemidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmemidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rmemidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBooksUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBooksUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBooksUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBooksUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBooksUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfinedayok;
    private javax.swing.JButton btnmemidok;
    private javax.swing.JButton btnrreturn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lrtotfine;
    private javax.swing.JTextField rbid1;
    private javax.swing.JTextField rbid2;
    private javax.swing.JTextField rdayfine;
    private javax.swing.JTextField rmemid;
    // End of variables declaration//GEN-END:variables
}
