/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teachercounselling;

/**
 *
 * @author Mijanur Rahman
 */
public class CheckByInitial extends javax.swing.JFrame {

    /**
     * Creates new form CheckByInitial
     */
    public CheckByInitial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1Show = new javax.swing.JLabel();
        jTextField1GetInitial = new javax.swing.JTextField();
        jButton4Check = new javax.swing.JButton();
        jButton2StudentLogin = new javax.swing.JButton();
        jButton3TeacherLogin = new javax.swing.JButton();
        jButton1Home = new javax.swing.JButton();
        jButton5Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 450));
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(null);

        jLabel1Show.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1Show.setForeground(new java.awt.Color(204, 255, 0));
        jLabel1Show.setText("Show counselling time by teacher initial:");
        getContentPane().add(jLabel1Show);
        jLabel1Show.setBounds(80, 70, 490, 100);

        jTextField1GetInitial.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(jTextField1GetInitial);
        jTextField1GetInitial.setBounds(240, 180, 140, 40);

        jButton4Check.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4Check.setForeground(new java.awt.Color(0, 0, 255));
        jButton4Check.setText("Check");
        jButton4Check.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton4Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4CheckActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4Check);
        jButton4Check.setBounds(270, 250, 80, 30);

        jButton2StudentLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2StudentLogin.setText("Student Login");
        jButton2StudentLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton2StudentLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2StudentLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2StudentLogin);
        jButton2StudentLogin.setBounds(300, 0, 130, 30);

        jButton3TeacherLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3TeacherLogin.setText("Teacher Login");
        jButton3TeacherLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton3TeacherLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3TeacherLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3TeacherLogin);
        jButton3TeacherLogin.setBounds(170, 0, 130, 30);

        jButton1Home.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1Home.setText("Home");
        jButton1Home.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton1Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1HomeActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Home);
        jButton1Home.setBounds(70, 0, 100, 30);

        jButton5Exit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5Exit.setForeground(new java.awt.Color(255, 0, 51));
        jButton5Exit.setText("Exit");
        jButton5Exit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton5Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5Exit);
        jButton5Exit.setBounds(0, 0, 70, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4CheckActionPerformed
        
    }//GEN-LAST:event_jButton4CheckActionPerformed

    private void jButton2StudentLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2StudentLoginActionPerformed
        StudentLogin.main();
    }//GEN-LAST:event_jButton2StudentLoginActionPerformed

    private void jButton3TeacherLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3TeacherLoginActionPerformed
        TeacherLogin.main();
    }//GEN-LAST:event_jButton3TeacherLoginActionPerformed

    private void jButton1HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1HomeActionPerformed
        String[] args = null;
        Home.main(args);
    }//GEN-LAST:event_jButton1HomeActionPerformed

    private void jButton5ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton5ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckByInitial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckByInitial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckByInitial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckByInitial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckByInitial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Home;
    private javax.swing.JButton jButton2StudentLogin;
    private javax.swing.JButton jButton3TeacherLogin;
    private javax.swing.JButton jButton4Check;
    private javax.swing.JButton jButton5Exit;
    private javax.swing.JLabel jLabel1Show;
    private javax.swing.JTextField jTextField1GetInitial;
    // End of variables declaration//GEN-END:variables
}
