/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teachercounselling;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mijanur Rahman
 */
public class SetSchedule extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    public SetSchedule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5Exit = new javax.swing.JButton();
        jButton1Home = new javax.swing.JButton();
        jButton3TeacherLogin = new javax.swing.JButton();
        jButton2StudentLogin = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        SetTime1 = new javax.swing.JTextField();
        SetTime2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SetTime3 = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        Message = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(650, 450));
        getContentPane().setLayout(null);

        jButton5Exit.setBackground(new java.awt.Color(204, 255, 204));
        jButton5Exit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5Exit.setForeground(new java.awt.Color(255, 0, 51));
        jButton5Exit.setText("Exit");
        jButton5Exit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton5Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5Exit);
        jButton5Exit.setBounds(0, 0, 70, 30);

        jButton1Home.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1Home.setText("Home");
        jButton1Home.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton1Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1HomeActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Home);
        jButton1Home.setBounds(70, 0, 100, 30);

        jButton3TeacherLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3TeacherLogin.setText("Teacher Login");
        jButton3TeacherLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton3TeacherLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3TeacherLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3TeacherLogin);
        jButton3TeacherLogin.setBounds(170, 0, 130, 30);

        jButton2StudentLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2StudentLogin.setText("Student Login");
        jButton2StudentLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton2StudentLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2StudentLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2StudentLogin);
        jButton2StudentLogin.setBounds(300, 0, 130, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 0));
        jLabel8.setText("Set Time1");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(130, 110, 80, 30);

        SetTime1.setBackground(new java.awt.Color(204, 255, 204));
        SetTime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetTime1ActionPerformed(evt);
            }
        });
        getContentPane().add(SetTime1);
        SetTime1.setBounds(210, 110, 140, 30);

        SetTime2.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(SetTime2);
        SetTime2.setBounds(210, 140, 140, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 0));
        jLabel5.setText("Set Time2");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 140, 80, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 0));
        jLabel7.setText("Set Time3");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(130, 170, 80, 30);

        SetTime3.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(SetTime3);
        SetTime3.setBounds(210, 170, 140, 30);

        Update.setBackground(new java.awt.Color(204, 255, 204));
        Update.setForeground(new java.awt.Color(0, 0, 255));
        Update.setText("Update");
        Update.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update);
        Update.setBounds(370, 140, 73, 23);

        Message.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Message.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(Message);
        Message.setBounds(210, 210, 200, 20);

        Table.setBackground(new java.awt.Color(204, 255, 204));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Saturday", "-", "-", "-"},
                {"Sunday", "-", "-", "-"},
                {"Monday", "-", "-", "-"},
                {"Tuesday", "-", "-", "-"},
                {"Wednestday", "-", "-", "-"},
                {"Thrusday", "-", "-", "-"},
                {"Friday", null, "-", "-"}
            },
            new String [] {
                "Day", "Time1", "Time2", "Time3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        Table.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                TableCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jScrollPane1.setViewportView(Table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 230, 500, 140);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton5ExitActionPerformed

    private void jButton1HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1HomeActionPerformed
        String[] args = null;
        Home.main(args);
    }//GEN-LAST:event_jButton1HomeActionPerformed

    private void jButton3TeacherLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3TeacherLoginActionPerformed
        TeacherLogin.main();
    }//GEN-LAST:event_jButton3TeacherLoginActionPerformed

    private void jButton2StudentLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2StudentLoginActionPerformed
        StudentLogin.main();
    }//GEN-LAST:event_jButton2StudentLoginActionPerformed

    private void SetTime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetTime1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SetTime1ActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        Message.setText("");
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        if(Table.getSelectedRow()==-1){
            if(Table.getRowCount()==1&&Table.getRowCount()==2&&Table.getRowCount()==3){
                Message.setText("Table is empty!");
            }else{
                Message.setText("You must select a day!");
            }
        }else{
            //model.setValueAt(SelectDay.getSelectedItem().toString(),Table.getSelectedRow(),0);
            model.setValueAt(SetTime1.getText(),Table.getSelectedRow(),1);
            model.setValueAt(SetTime2.getText(),Table.getSelectedRow(),2);
            model.setValueAt(SetTime3.getText(),Table.getSelectedRow(),3);
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        //SelectDay.setSelectedItem(model.getValueAt(Table.getSelectedRow(),0).toString());
        SetTime1.setText(model.getValueAt(Table.getSelectedRow(),1).toString());
        SetTime2.setText(model.getValueAt(Table.getSelectedRow(),2).toString());
        SetTime3.setText(model.getValueAt(Table.getSelectedRow(),3).toString());
    }//GEN-LAST:event_TableMouseClicked

    private void TableCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_TableCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_TableCaretPositionChanged

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetSchedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Message;
    private javax.swing.JTextField SetTime1;
    private javax.swing.JTextField SetTime2;
    private javax.swing.JTextField SetTime3;
    private javax.swing.JTable Table;
    private javax.swing.JButton Update;
    private javax.swing.JButton jButton1Home;
    private javax.swing.JButton jButton2StudentLogin;
    private javax.swing.JButton jButton3TeacherLogin;
    private javax.swing.JButton jButton5Exit;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
