/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teachercounselling;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Mijanur Rahman
 */
public class StudentRegister extends javax.swing.JFrame {
    Connection conn = null;
    /**
     * Creates new form StudentRegister
     */
    public StudentRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonHome4 = new javax.swing.JButton();
        TeacherLogin2 = new javax.swing.JButton();
        StudentLogin2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        getName = new javax.swing.JTextField();
        Studentid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Studentpass = new javax.swing.JPasswordField();
        Srudentreg = new javax.swing.JButton();
        jButtonExit4 = new javax.swing.JButton();
        Message = new javax.swing.JLabel();
        Serial = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Register System");
        setMinimumSize(new java.awt.Dimension(650, 450));
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(null);

        jButtonHome4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonHome4.setText("Home");
        jButtonHome4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonHome4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHome4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHome4);
        jButtonHome4.setBounds(70, 0, 100, 30);

        TeacherLogin2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TeacherLogin2.setText("Teacher Login");
        TeacherLogin2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        TeacherLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherLogin2ActionPerformed(evt);
            }
        });
        getContentPane().add(TeacherLogin2);
        TeacherLogin2.setBounds(170, 0, 130, 30);

        StudentLogin2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        StudentLogin2.setText("Student Login");
        StudentLogin2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        StudentLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentLogin2ActionPerformed(evt);
            }
        });
        getContentPane().add(StudentLogin2);
        StudentLogin2.setBounds(300, 0, 130, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 0));
        jLabel1.setText("Register Student");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 70, 270, 50);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 0));
        jLabel4.setText("Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(170, 140, 90, 30);

        getName.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(getName);
        getName.setBounds(300, 140, 190, 30);

        Studentid.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(Studentid);
        Studentid.setBounds(300, 190, 190, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 0));
        jLabel3.setText("ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 190, 90, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 0));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 240, 120, 30);

        Studentpass.setBackground(new java.awt.Color(204, 255, 204));
        Studentpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentpassActionPerformed(evt);
            }
        });
        getContentPane().add(Studentpass);
        Studentpass.setBounds(300, 240, 190, 30);

        Srudentreg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Srudentreg.setForeground(new java.awt.Color(0, 0, 255));
        Srudentreg.setText("Register");
        Srudentreg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Srudentreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SrudentregActionPerformed(evt);
            }
        });
        getContentPane().add(Srudentreg);
        Srudentreg.setBounds(350, 300, 100, 30);

        jButtonExit4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonExit4.setForeground(new java.awt.Color(255, 0, 51));
        jButtonExit4.setText("Exit");
        jButtonExit4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonExit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExit4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit4);
        jButtonExit4.setBounds(0, 0, 70, 30);

        Message.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(Message);
        Message.setBounds(300, 270, 190, 20);
        getContentPane().add(Serial);
        Serial.setBounds(470, 80, 130, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHome4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHome4ActionPerformed
        String[] args = null;
            Home.main(args);
    }//GEN-LAST:event_jButtonHome4ActionPerformed

    private void TeacherLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherLogin2ActionPerformed
        TeacherLogin.main();
    }//GEN-LAST:event_TeacherLogin2ActionPerformed

    private void StudentLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentLogin2ActionPerformed
            StudentLogin.main();
    }//GEN-LAST:event_StudentLogin2ActionPerformed

    private void jButtonExit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExit4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonExit4ActionPerformed

    private void SrudentregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SrudentregActionPerformed
        try{
            
             conn=Test.ConnectrDb();
            String query = "insert into admin(Serial,Initial,Username,Password)"+"values(?,?,?,?)";
            PreparedStatement pst =conn.prepareStatement(query);
            if(Serial.getText().equals("")){
                pst.setString(1, null);
            }else{
               
                pst.setString(1, Serial.getText());
            }
            pst.setString(2, getName.getText());
            pst.setString(3, Studentid.getText());
            pst.setString(4, Studentpass.getText());
            pst.execute();
            pst.close();
            JOptionPane.showMessageDialog(null, "Signup Succesfull!");
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_SrudentregActionPerformed

    private void StudentpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Message;
    private javax.swing.JTextField Serial;
    private javax.swing.JButton Srudentreg;
    private javax.swing.JButton StudentLogin2;
    private javax.swing.JTextField Studentid;
    private javax.swing.JPasswordField Studentpass;
    private javax.swing.JButton TeacherLogin2;
    private javax.swing.JTextField getName;
    private javax.swing.JButton jButtonExit4;
    private javax.swing.JButton jButtonHome4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
