/*
 * Copyright (c) Team Extreme. All rights reserved.
 * Technologies  * 
 * Language - JAVA  * 
 * Database - MySQL  * 
 */
package school_management.staff_management;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import school_management.DBConn;

/**
 *
 * @author AIA Insurance
 */
public class LeaveDetails extends javax.swing.JFrame {

    /**
     * Creates new form LeaveDetails
     */
     ResultSet rs=null;
     viewLeaveRequest vw;
    
    public LeaveDetails() {
        
        initComponents();
       // fillFields();
    }
    public LeaveDetails(int leaveId,viewLeaveRequest vw) {
        
        initComponents();
        this.vw=vw;
        fillFields(leaveId);
    }

    private void fillFields(int leaveId){
        
         
         try {
            String sql = "select * from EmpLeaveRequest where LeaveId= ?";
            PreparedStatement pst = DBConn.myConn().prepareStatement(sql);
            pst.setInt(1,leaveId);
            rs = pst.executeQuery();
            if(rs.next()){
            txtLeaveId.setText(Integer.toString(rs.getInt("LeaveId")));
            txtStaffId.setText(Integer.toString(rs.getInt("staff_Id")));
            txtName.setText(rs.getString("FirstName"));
            txtAppliedDate.setText(rs.getDate("ApplyDate").toString());
            txtAvailable.setText(Integer.toString(rs.getInt("AvailableBalanceBefore")));
            txtStartDate.setText(rs.getDate("LeaveStartDate").toString());
            txtEndDate.setText(rs.getDate("LeaveEndDate").toString());
            txtNoOfDays.setText(Integer.toString(rs.getInt("NoOfDays")));
            txtRemaining.setText(Integer.toString(rs.getInt("AvailableBalanceAfter")));
            }
                                     
        } catch (SQLException e) {
            System.out.println(e);         
        }
         catch (Exception e) {
            System.out.println(e);         
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblStaffId = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAvailable = new javax.swing.JLabel();
        lblStartDate = new javax.swing.JLabel();
        lblEndDate = new javax.swing.JLabel();
        lblNoOfDays = new javax.swing.JLabel();
        lblRemaining = new javax.swing.JLabel();
        txtStaffId = new javax.swing.JTextField();
        txtAvailable = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtStartDate = new javax.swing.JTextField();
        txtEndDate = new javax.swing.JTextField();
        txtNoOfDays = new javax.swing.JTextField();
        txtRemaining = new javax.swing.JTextField();
        lblAvailable1 = new javax.swing.JLabel();
        txtAppliedDate = new javax.swing.JTextField();
        lblStaffId1 = new javax.swing.JLabel();
        txtLeaveId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblStaffId.setText("Staff ID");

        lblName.setText("Staff Name");

        lblAvailable.setText("Available Balance");

        lblStartDate.setText("Start Date (Inclusive)");

        lblEndDate.setText("End Date (Inclusive)");

        lblNoOfDays.setText("No.Of Days");

        lblRemaining.setText("Remaining Balance");

        txtStaffId.setEditable(false);
        txtStaffId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStaffIdActionPerformed(evt);
            }
        });

        txtAvailable.setEditable(false);

        txtName.setEditable(false);

        txtStartDate.setEditable(false);

        txtEndDate.setEditable(false);

        txtNoOfDays.setEditable(false);

        txtRemaining.setEditable(false);

        lblAvailable1.setText("Applied Date");

        txtAppliedDate.setEditable(false);

        lblStaffId1.setText("Leave ID");

        txtLeaveId.setEditable(false);
        txtLeaveId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLeaveIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblStaffId1)
                        .addGap(136, 136, 136)
                        .addComponent(txtLeaveId, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStaffId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(125, 125, 125)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName)
                            .addComponent(txtStaffId)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblStartDate)
                                .addComponent(lblAvailable, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblEndDate, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNoOfDays, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblRemaining, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lblAvailable1))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAppliedDate)
                            .addComponent(txtRemaining, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNoOfDays, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEndDate, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStartDate, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAvailable, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStaffId1)
                    .addComponent(txtLeaveId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStaffId)
                    .addComponent(txtStaffId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAppliedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvailable1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvailable, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAvailable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStartDate)
                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndDate)
                    .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoOfDays)
                    .addComponent(txtNoOfDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRemaining)
                    .addComponent(txtRemaining, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jButton1.setText("Approve");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reject");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jButton1)
                .addGap(81, 81, 81)
                .addComponent(jButton2)
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(429, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(52, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtStaffIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStaffIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStaffIdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         updateLeaveBalance();
         DeleteLeaveRequest();
         this.vw.tableLoad();
         this.setVisible(false);
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void updateLeaveBalance(){
        
        try {
            String sql = "update EmpLeave set LeaveBalance=? where staff_Id = ?";
            PreparedStatement pst = DBConn.myConn().prepareStatement(sql);
            pst.setInt(1,Integer.parseInt(txtRemaining.getText()));
            pst.setInt(2,Integer.parseInt(txtStaffId.getText()));
             
            pst.executeUpdate();
//            txtStaffId.setText(Integer.toString(rs.getInt("staff_Id")));
//            txtName.setText(rs.getString("FirstName"));
//            txtAppliedDate.setText(rs.getDate("ApplyDate").toString());
//            txtAvailable.setText(Integer.toString(rs.getInt("AvailableBalanceBefore")));
//            txtStartDate.setText(rs.getDate("LeaveStartDate").toString());
//            txtEndDate.setText(rs.getDate("LeaveEndDate").toString());
//            txtNoOfDays.setText(Integer.toString(rs.getInt("NoOfDays")));
//            txtRemaining.setText(Integer.toString(rs.getInt("AvailableBalanceAfter")));
                                     
        } catch (SQLException e) {
            System.out.println(e);         
        }
         catch (Exception e) {
            System.out.println(e);         
        }
        
    }
    
    private void DeleteLeaveRequest(){
        
        try {
            String sql = "delete from EmpLeaveRequest where LeaveId = ?";
            PreparedStatement pst = DBConn.myConn().prepareStatement(sql);
            pst.setInt(1,Integer.parseInt(txtLeaveId.getText()));
            
            pst.execute();
            
                                     
        } catch (SQLException e) {
            System.out.println(e);         
        }
         catch (Exception e) {
            System.out.println(e);         
        }
        
    }
    private void txtLeaveIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLeaveIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLeaveIdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DeleteLeaveRequest();
        this.vw.tableLoad();
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeaveDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeaveDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeaveDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeaveDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeaveDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAvailable;
    private javax.swing.JLabel lblAvailable1;
    private javax.swing.JLabel lblEndDate;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNoOfDays;
    private javax.swing.JLabel lblRemaining;
    private javax.swing.JLabel lblStaffId;
    private javax.swing.JLabel lblStaffId1;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JTextField txtAppliedDate;
    private javax.swing.JTextField txtAvailable;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtLeaveId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNoOfDays;
    private javax.swing.JTextField txtRemaining;
    private javax.swing.JTextField txtStaffId;
    private javax.swing.JTextField txtStartDate;
    // End of variables declaration//GEN-END:variables
}
