/*
 * Copyright (c) Team Extreme. All rights reserved.
 * Technologies  * 
 * Language - JAVA  * 
 * Database - MySQL  * 
 */
package school_management.staff_management;

import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import school_management.DBConn;

/**
 *
 * @author User
 */
public class ManageStaff extends javax.swing.JFrame {

    ResultSet rs=null;
    
    /**
     * Creates new form ManageStaff
     */
    public ManageStaff() {
        initComponents();
        tableload();
    }
    
    public boolean tableload() {

        try {
            String sql = "select staff_Id as 'Staff ID',firstName as 'First Name',mobile as 'Contact',email as 'Email',currentAdd as 'Address'from staff_table";
            PreparedStatement pst = DBConn.myConn().prepareStatement(sql);
            rs = pst.executeQuery();
            
            DefaultTableModel tableModel = (DefaultTableModel) DbUtils.resultSetToTableModel(rs);
             tableModel.addColumn("Update");
             tableModel.addColumn("Delete");
             for(int i=0;i<tableModel.getRowCount();i++){
                 tableModel.setValueAt("Update", i, 5);
                 tableModel.setValueAt("Delete", i, 6);
                 
             }
          //  tableStaff.setModel(DbUtils.resultSetToTableModel(rs));
            tableStaff.setModel(tableModel);
            
            return true;
            
        } catch (Exception e) {
            System.out.println(e);
            return false;
        }

    }
    
 public void mouseClicked(java.awt.event.MouseEvent event) {
   
     
 }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableStaff = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtFname = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableStaffMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableStaff);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        txtFname.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtFnameInputMethodTextChanged(evt);
            }
        });
        txtFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFnameActionPerformed(evt);
            }
        });
        txtFname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFnameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFnameKeyTyped(evt);
            }
        });

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("First Name");

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel1))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableStaffMouseClicked
        // TODO add your handling code here:
         int row = tableStaff.rowAtPoint(evt.getPoint());
    int col = tableStaff.columnAtPoint(evt.getPoint());
    
    if(col==5){
        
        int response=JOptionPane.showConfirmDialog(null,"Do you really want to Update the selected Staff?");
        if(response == 0){
            
            RegisterStaff rg=new RegisterStaff();
            rg.setVisible(true);
            rg.setData(Integer.parseInt(tableStaff.getValueAt(row, 0).toString()),this);
            
        }
    }
    else if(col==6){
        
        int response=JOptionPane.showConfirmDialog(null,"Do you really want to Delete the selected Staff?");
        if(response == 0){
            
           staffModel sm=new staffModel();
            sm.setStaffId(tableStaff.getValueAt(row,0).toString());
            sm.deleteStaff();
            tableload();
        }
        
    }
    
     
    }//GEN-LAST:event_tableStaffMouseClicked

    private void searchById(){
        
//        try{
//            staffModel st=new staffModel();
//            rs=st.searchStaffById(Integer.parseInt(txtStaffId.getText()));
//            
//            DefaultTableModel tableModel = (DefaultTableModel) DbUtils.resultSetToTableModel(rs);
//            System.out.println(tableModel.getRowCount());
//            if(tableModel.getRowCount()>0){
//             tableModel.addColumn("Update");
//             tableModel.addColumn("Delete");
//             for(int i=0;i<tableModel.getRowCount();i++){
//                 tableModel.setValueAt("Update", i, 5);
//                 tableModel.setValueAt("Delete", i, 6);
//                 
//             }
//          //  tableStaff.setModel(DbUtils.resultSetToTableModel(rs));
//            tableStaff.setModel(tableModel);
//            }
//            
//        }
//        catch(NumberFormatException | HeadlessException ex){
//            
//        }
//        catch(Exception ex){
//            
//        }
    }
    
     private void searchByName(){
        
        try{
            staffModel st=new staffModel();
            rs=st.searchStaffByFname(txtFname.getText());
            
            DefaultTableModel tableModel = (DefaultTableModel) DbUtils.resultSetToTableModel(rs);
            System.out.println(tableModel.getRowCount());
            
            if(tableModel.getRowCount()>0){
             tableModel.addColumn("Update");
             tableModel.addColumn("Delete");
             for(int i=0;i<tableModel.getRowCount();i++){
                 tableModel.setValueAt("Update", i, 5);
                 tableModel.setValueAt("Delete", i, 6);
                 
             }
          //  tableStaff.setModel(DbUtils.resultSetToTableModel(rs));
            tableStaff.setModel(tableModel);
            }
            
        }
        catch(NumberFormatException | HeadlessException ex){
            
        }
        catch(Exception ex){
            
        }
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        searchByName();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtFnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFnameKeyTyped
        // TODO add your handling code here:
        searchByName();
    }//GEN-LAST:event_txtFnameKeyTyped

    private void txtFnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFnameKeyPressed
        // TODO add your handling code here:
         //searchByName();
    }//GEN-LAST:event_txtFnameKeyPressed

    private void txtFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFnameActionPerformed

    private void txtFnameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtFnameInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFnameInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableStaff;
    private javax.swing.JTextField txtFname;
    // End of variables declaration//GEN-END:variables
}
